readme:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - assets/**

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**

visual:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - assets/**

governance:
  - changed-files:
      - any-glob-to-any-file:
          - .github/CODEOWNERS
          - .github/pull_request_template.md
          - .github/ISSUE_TEMPLATE/**
          - GOVERNANCE.md

maintenance:
  - changed-files:
      - any-glob-to-any-file:
          - .github/dependabot.yml
          - .markdownlint.json
          - .lycheeignore
          - .gitignore
          - SECURITY.md
